config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :users, only: [:show] do
    member do
      get :following, :followers
    end
  end
  resources :follow_relationships, only: [:create, :destroy]
  resources :posts do
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :notifications, only: [:index, :destroy]
  resources :tags do
    get 'posts' => 'posts#tags'
    post 'posts' => 'posts#tags'
  end
  post '/posts/:post_id/likes' => 'likes#create'
  delete '/posts/:post_id/likes' => 'likes#destroy'
  get '/search', to: 'posts#search'
  resources :records
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :post, optional: true
  belongs_to :comment, optional: true
  belongs_to :visitor, foreign_key: "visitor_id", class_name: "User", optional: true
  belongs_to :visited, foreign_key: "visited_id", class_name: "User", optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(10)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end

  def destroy
    @notifications = current_user.passive_notifications.destroy_all
    redirect_to notifications_path
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def notification_form(notification)
    # 通知を送ってきたユーザーを取得
    visitor = notification.visitor
    # notification.actionがfollowかlikeかcommentかで処理を変える
    case notification.action
    when 'follow'
      # aタグで通知を作成したユーザーshowのリンクを作成
      tag.a(notification.visitor.username, href: user_path(visitor)) + 'があなたをフォローしました'
    when 'like'
      tag.a(notification.visitor.username, href: user_path(visitor)) + 'が' +
        tag.a('あなたの投稿', href: post_path(notification.post_id)) + 'にいいねしました'
    when 'comment'
      # コメントの内容と投稿のタイトルを取得
      tag.a(visitor.username, href: user_path(visitor)) + 'が' + tag.a('あなたの投稿', href: post_path(notification.post_id)) + 'にコメントしました'
    end
  end
end

app/views/notifications/_notification.html.erb
<div class="notification-view">
  <div class="notification-content">
    <div class="text-dark mt-5">
      <%= notification_form(notification) %>
    </div>

    <div class="text-center mt-2">      
      <div class="moderate-font text-right border-bottom">
        <%# 通知の作成時間 %>
        <%= " (#{time_ago_in_words(notification.created_at)}前)" %>
      </div>
    </div>
  </div>
</div>

app/views/notifications/index.html.erb
<div class="container-fluid py-4 mw-md">
  <div class="notification-contents">
    <% if @notifications.exists? %>
      <div class="text-center mt-5">
          <%= link_to notification_path(@notifications), method: :delete, class: "link text-warning" do %>
            <i class="fas fa-trash mr-1"></i>確認済みにする
          <% end %>
      </div>
      <div class="notification-index">
        <%= render @notifications %>
      </div>
    <% else %>
        <p class="mt-5 text-center">お知らせはありません</p>
    <% end %>
  </div>
</div>