config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :users, only: [:show] do
    member do
      get :following, :followers
    end
  end
  resources :follow_relationships, only: [:create, :destroy]
  resources :posts do
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :notifications, only: [:index, :destroy]
  resources :tags do
    get 'posts' => 'posts#tags'
    post 'posts' => 'posts#tags'
  end
  post '/posts/:post_id/likes' => 'likes#create'
  delete '/posts/:post_id/likes' => 'likes#destroy'
  get '/search', to: 'posts#search'
  resources :records
end

app/models/record.rb
class Record < ApplicationRecord
  paginates_per 3

  geocoded_by :place
  after_validation :geocode, if: :place_changed?

  after_initialize :set_default_values

  belongs_to :user

  validates :place, length: { maximum: 20 }

  with_options presence: true do
    validates :user_id
  end

  with_options length: { maximum: 12 } do
    validates :name_a, presence: true
    validates :name_b
    validates :name_c
    validates :enemyname_a
    validates :enemyname_b
    validates :enemyname_c
  end

  with_options length: { maximum: 15 } do
    validates :teamname
    validates :enemyteam
    validates :title
  end

  with_options allow_blank: true, numericality: { in: 0..12 } do
    validates :score_1
    validates :score_2
    validates :score_3
    validates :score_4
    validates :score_5
    validates :score_6
    validates :score_7
    validates :score_8
    validates :score_9
    validates :score_10
    validates :enemyscore_1
    validates :enemyscore_2
    validates :enemyscore_3
    validates :enemyscore_4
    validates :enemyscore_5
    validates :enemyscore_6
    validates :enemyscore_7
    validates :enemyscore_8
    validates :enemyscore_9
    validates :enemyscore_10
  end

  private

  def set_default_values
    self.score_1 ||= 0
    self.score_2 ||= 0
    self.score_3 ||= 0
    self.score_4 ||= 0
    self.score_5 ||= 0
    self.score_6 ||= 0
    self.score_7 ||= 0
    self.score_8 ||= 0
    self.score_9 ||= 0
    self.score_10 ||= 0
    self.enemyscore_1 ||= 0
    self.enemyscore_2 ||= 0
    self.enemyscore_3 ||= 0
    self.enemyscore_4 ||= 0
    self.enemyscore_5 ||= 0
    self.enemyscore_6 ||= 0
    self.enemyscore_7 ||= 0
    self.enemyscore_8 ||= 0
    self.enemyscore_9 ||= 0
    self.enemyscore_10 ||= 0
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_record, only: [:update, :destroy]
  before_action :record_current_user, only: [:edit, :update, :destroy]

  def new
    @record = Record.new
  end

  def create
    @record = current_user.records.build(record_params)
    if @record.save
      flash[:success] = "スコアを投稿しました！"
      redirect_to user_path(current_user)
    else
      render new_record_path
    end
  end

  def show
    @record = Record.find(params[:id])
    @records = Record.where(id: params[:id])
    @records.each do |record|
      @half_enemyscore = record.enemyscore_1 + record.enemyscore_2 + record.enemyscore_3 + record.enemyscore_4 + record.enemyscore_5
      @half_score = record.score_1 + record.score_2 + record.score_3 + record.score_4 + record.score_5
    end
    # myscore
    if @half_score > Const::WIN_SCORE
      @total_score = Const::OVER_FIFTY_SCORE + @record.score_6 + @record.score_7 + @record.score_8 + @record.score_9 + @record.score_10
    elsif @half_score + @record.score_6 > Const::WIN_SCORE
      @total_score = Const::OVER_FIFTY_SCORE + @record.score_7 + @record.score_8 + @record.score_9 + @record.score_10
    elsif @half_score + @record.score_6 + @record.score_7 > Const::WIN_SCORE
      @total_score = Const::OVER_FIFTY_SCORE + @record.score_8 + @record.score_9 + @record.score_10
    elsif @half_score + @record.score_6 + @record.score_7 + @record.score_8 > Const::WIN_SCORE
      @total_score = Const::OVER_FIFTY_SCORE + @record.score_9 + @record.score_10
    elsif @half_score + @record.score_6 + @record.score_7 + @record.score_8 + @record.score_9 > Const::WIN_SCORE
      @total_score = Const::OVER_FIFTY_SCORE + @record.score_10
    elsif @half_score + @record.score_6 + @record.score_7 + @record.score_8 + @record.score_9 + @record.score_10 > Const::WIN_SCORE
      @total_score = Const::OVER_FIFTY_SCORE
    else
      @total_score = @half_score + @record.score_6 + @record.score_7 + @record.score_8 + @record.score_9 + @record.score_10
    end
    # enemyscore
    if @half_enemyscore > Const::WIN_SCORE
      @total_enemyscore = Const::OVER_FIFTY_SCORE + @record.enemyscore_6 + @record.enemyscore_7 + @record.enemyscore_8 +
        @record.enemyscore_9 + @record.enemyscore_10
    elsif @half_enemyscore + @record.enemyscore_6 > Const::WIN_SCORE
      @total_enemyscore = Const::OVER_FIFTY_SCORE + @record.enemyscore_7 + @record.enemyscore_8 +
        @record.enemyscore_9 + @record.enemyscore_10
    elsif @half_enemyscore + @record.enemyscore_6 + @record.enemyscore_7 > Const::WIN_SCORE
      @total_enemyscore = Const::OVER_FIFTY_SCORE + @record.enemyscore_8 + @record.enemyscore_9 + @record.enemyscore_10
    elsif @half_enemyscore + @record.enemyscore_6 + @record.enemyscore_7 + @record.enemyscore_8 > Const::WIN_SCORE
      @total_enemyscore = Const::OVER_FIFTY_SCORE + @record.enemyscore_9 + @record.enemyscore_10
    elsif @half_enemyscore + @record.enemyscore_6 + @record.enemyscore_7 + @record.enemyscore_8 + @record.enemyscore_9 > Const::WIN_SCORE
      @total_enemyscore = Const::OVER_FIFTY_SCORE + @record.enemyscore_10
    elsif @half_enemyscore + @record.enemyscore_6 + @record.enemyscore_7 + @record.enemyscore_8 +
        @record.enemyscore_9 + @record.enemyscore_10 > Const::WIN_SCORE
      @total_enemyscore = Const::OVER_FIFTY_SCORE
    else
      @total_score = @half_score + @record.score_6 + @record.score_7 + @record.score_8 + @record.score_9 + @record.score_10
    end
  end

  def edit
    @record = Record.find(params[:id])
    @records = Record.where(id: params[:id])
  end

  def update
    @record = Record.find(params[:id])
    if @record.update(record_params)
      flash[:success] = "スコアを更新しました！"
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @record = Record.find(params[:id])
    if @record.destroy
      redirect_to root_path
      flash[:success] = "スコアを削除しました！"
    else
      render :show
    end
  end

  private

  def set_record
    @score_record = Record.find_by(user_id: current_user.id)
  end

  def record_params
    params.require(:record).permit(:title, :place, :name_a, :name_b, :name_c, :teamname,
                                   :enemyname_a, :enemyname_b, :enemyname_c, :enemyteam,
                                   :score_1, :score_2, :score_3, :score_4, :score_5,
                                   :score_6, :score_7, :score_8, :score_9, :score_10,
                                   :enemyscore_1, :enemyscore_2, :enemyscore_3, :enemyscore_4, :enemyscore_5,
                                   :enemyscore_6, :enemyscore_7, :enemyscore_8, :enemyscore_9,
                                   :enemyscore_10).merge(user_id: current_user.id)
  end

  def record_current_user
    @records = current_user.records
    @record = @records.find_by(id: params[:id])
    redirect_to new_record_path unless @record
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_record.html.erb
<div class="container-fluid py-4 mw-md">
  <div class="border-bottom">
    <%= link_to "/records/#{record.id}" do %>
      <div class="post-contents">
        <% if record.title.present? %>
          <p class="text-dark"><i class="fas fa-crown"></i><%= record.title %><i class="fas fa-crown"></i></p>
        <% else %>
          <p class="text-dark">No title</p>
        <% end %>
      </div>
      <div class="text-center">
        <p class="text-dark"><i class="fas fa-map-pin"></i> :
          <% if record.place.present? %>
            <%= record.place %>
          <% end %>
        </p>
      </div>
      <div class="text-center">
        <p class="text-dark">
          <% if record.enemyteam.present? %>
            <%= record.teamname %> VS <%= record.enemyteam %>
          <% else %>
            <%= record.name_a %>
          <% end %>
        </p>
      </div>
      <p class="record-time text-right"><%= time_ago_in_words(record.created_at) %>前</p>
    <% end %>
  </div>
</div>

app/views/records/edit.html.erb
<div class="container-fluid py-4 mw-md">
  <%= form_with(model: @record, url: record_path(@record), method: :patch, local: true) do |f| %>
    <div class="form-group pt-5 mt-5">
      <h4>大会名</h4>
      <%= f.text_field :title, placeholder: "例)MolkkyRecord CUP", class: "form-control" %>
    </div>
    <div class="d-flex justify-content-center">
      <div class="form-group mt-5">
        <h4 class="score-content">チーム名(自)</h4>
        <%= f.text_field :teamname, placeholder: "例)チーム大阪", class: "form-control" %>
      </div>
      <div class="form-group mt-5 ml-5">
        <h4 class="score-content">チーム名(相)</h4>
        <%= f.text_field :enemyteam, placeholder: "例)チーム京都", class: "form-control" %>
      </div>
    </div>
    <div class="d-flex justify-content-center">
      <div class="form-group mt-5">
        <h4 class="score-content">名前(自)</h4>
        <%= f.text_field :name_a, placeholder: "例)大阪 太郎", class: "form-control" %>
        <%= f.text_field :name_b, placeholder: "例)大阪 次郎", class: "form-control" %>
        <%= f.text_field :name_c, class: "form-control" %>
      </div>
      <div class="form-group mt-5 ml-5">
        <h4 class="score-content">名前(相)</h4>
        <%= f.text_field :enemyname_a, placeholder: "例)京都 太郎", class: "form-control" %>
        <%= f.text_field :enemyname_b, placeholder: "例)京都 次郎", class: "form-control" %>
        <%= f.text_field :enemyname_c, class: "form-control" %>
      </div>
    </div>
    <div class="form-group mt-5">
      <h4>場所</h4>
      <%= f.text_field :place, placeholder: "例)三角公園 京都府宇治市", class: "form-control" %>
    </div>
    <div class="d-flex justify-content-center">
      <div class="form-group mt-5">
        <h4 class="score-content">スコア(自)</h4>
        <ol class="score-number">
          <li><%= f.number_field :score_1, min: 0, max: 12, class: "form-control" %></li>
          <li><%= f.number_field :score_2, min: 0, max: 12, class: "form-control" %></li>
          <li><%= f.number_field :score_3, min: 0, max: 12, class: "form-control" %></li>
          <li><%= f.number_field :score_4, min: 0, max: 12, class: "form-control" %></li>
          <li><%= f.number_field :score_5, min: 0, max: 12, class: "form-control" %></li>
          <li><%= f.number_field :score_6, min: 0, max: 12, class: "form-control" %></li>
          <li><%= f.number_field :score_7, min: 0, max: 12, class: "form-control" %></li>
          <li><%= f.number_field :score_8, min: 0, max: 12, class: "form-control" %></li>
          <li><%= f.number_field :score_9, min: 0, max: 12, class: "form-control" %></li>
          <li><%= f.number_field :score_10, min: 0, max: 12, class: "form-control" %></li>
        </ol>
      </div>
      <div class="form-group mt-5 ml-5">
        <h4 class="score-content">スコア(相)</h4>
        <ol class="score-number">
          <li><%= f.number_field :enemyscore_1, min: 0, max: 12, class: "form-control" %></li>    
          <li><%= f.number_field :enemyscore_2, min: 0, max: 12, class: "form-control" %></li>    
          <li><%= f.number_field :enemyscore_3, min: 0, max: 12, class: "form-control" %></li>    
          <li><%= f.number_field :enemyscore_4, min: 0, max: 12, class: "form-control" %></li>    
          <li><%= f.number_field :enemyscore_5, min: 0, max: 12, class: "form-control" %></li>    
          <li><%= f.number_field :enemyscore_6, min: 0, max: 12, class: "form-control" %></li>    
          <li><%= f.number_field :enemyscore_7, min: 0, max: 12, class: "form-control" %></li>    
          <li><%= f.number_field :enemyscore_8, min: 0, max: 12, class: "form-control" %></li>    
          <li><%= f.number_field :enemyscore_9, min: 0, max: 12, class: "form-control" %></li>    
          <li><%= f.number_field :enemyscore_10, min: 0, max: 12, class: "form-control" %></li>    
        </ol>
      </div>
    </div>
    <div class="form-group mt-5 text-center">
      <%= f.submit "更新する", class: "btn p-2 pl-5 pr-5 text-white" %>
    </div>
    <%= link_to t("戻る"), :back, class: "text-center text-dark" %>
  <% end %>
</div>

app/views/records/new.html.erb
<div class="container-fluid py-4 mw-md">
  <%= form_with(model: @record, local: true) do |f| %>
    <div class="form-group pt-5 mt-5">
      <h4>大会名</h4>
      <%= f.text_field :title, placeholder: "例)MolkkyRecord CUP", class: "form-control" %>
    </div>
    <div class="d-flex justify-content-center">
      <div class="form-group mt-5">
        <h4 class="score-content">チーム名(自)</h4>
        <%= f.text_field :teamname, placeholder: "例)チーム大阪", class: "form-control" %>
      </div>
      <div class="form-group mt-5 ml-5">
        <h4 class="score-content">チーム名(相)</h4>
        <%= f.text_field :enemyteam, placeholder: "例)チーム京都", class: "form-control" %>
      </div>
    </div>
    <div class="d-flex justify-content-center">
      <div class="form-group mt-5">
        <h4 class="score-content">名前(自)</h4>
        <%= f.text_field :name_a, placeholder: "例)大阪 太郎", class: "form-control" %>
        <%= f.text_field :name_b, placeholder: "例)大阪 次郎", class: "form-control" %>
        <%= f.text_field :name_c, class: "form-control" %>
      </div>
      <div class="form-group mt-5 ml-5">
        <h4 class="score-content">名前(相)</h4>
        <%= f.text_field :enemyname_a, placeholder: "例)京都 太郎", class: "form-control" %>
        <%= f.text_field :enemyname_b, placeholder: "例)京都 次郎", class: "form-control" %>
        <%= f.text_field :enemyname_c, class: "form-control" %>
      </div>
    </div>
    <div class="form-group mt-5">
      <h4>場所</h4>
      <%= f.text_field :place, placeholder: "例)三角公園 京都府宇治市", class: "form-control" %>
    </div>
    <div class="d-flex justify-content-center">
      <div class="form-group mt-5">
        <h4 class="score-content">スコア(自)</h4>
        <ol class="score-number">
          <li><%= f.number_field :score_1, min: 0, max: 12, class: "form-control" %></li>
          <li><%= f.number_field :score_2, min: 0, max: 12, class: "form-control" %></li>
          <li><%= f.number_field :score_3, min: 0, max: 12, class: "form-control" %></li>
          <li><%= f.number_field :score_4, min: 0, max: 12, class: "form-control" %></li>
          <li><%= f.number_field :score_5, min: 0, max: 12, class: "form-control" %></li>
          <li><%= f.number_field :score_6, min: 0, max: 12, class: "form-control" %></li>
          <li><%= f.number_field :score_7, min: 0, max: 12, class: "form-control" %></li>
          <li><%= f.number_field :score_8, min: 0, max: 12, class: "form-control" %></li>
          <li><%= f.number_field :score_9, min: 0, max: 12, class: "form-control" %></li>
          <li><%= f.number_field :score_10, min: 0, max: 12, class: "form-control" %></li>
        </ol>
      </div>
      <div class="form-group mt-5 ml-5">
        <h4 class="score-content">スコア(相)</h4>
        <ol class="score-number">
          <li><%= f.number_field :enemyscore_1, min: 0, max: 12, class: "form-control" %></li>    
          <li><%= f.number_field :enemyscore_2, min: 0, max: 12, class: "form-control" %></li>    
          <li><%= f.number_field :enemyscore_3, min: 0, max: 12, class: "form-control" %></li>    
          <li><%= f.number_field :enemyscore_4, min: 0, max: 12, class: "form-control" %></li>    
          <li><%= f.number_field :enemyscore_5, min: 0, max: 12, class: "form-control" %></li>    
          <li><%= f.number_field :enemyscore_6, min: 0, max: 12, class: "form-control" %></li>    
          <li><%= f.number_field :enemyscore_7, min: 0, max: 12, class: "form-control" %></li>    
          <li><%= f.number_field :enemyscore_8, min: 0, max: 12, class: "form-control" %></li>    
          <li><%= f.number_field :enemyscore_9, min: 0, max: 12, class: "form-control" %></li>    
          <li><%= f.number_field :enemyscore_10, min: 0, max: 12, class: "form-control" %></li>    
        </ol>
      </div>
    </div>
    <div class="form-group mt-5 text-center">
      <%= f.submit "投稿する", class: "btn p-2 pl-5 pr-5 text-white" %>
    </div>
    <%= link_to t("戻る"), :back, class: "text-center text-dark" %>
  <% end %>
</div>

app/views/records/show.html.erb
<div class="container-fluid py-4 mw-md">
  <div class="text-center mt-5">
    <h4><i class="fas fa-crown"></i>大会名<i class="fas fa-crown"></i></h4>
    <% if @record.title.present? %>
      <span>~<%= @record.title %>~</span>
    <% else %>
      <span>~No title~</span>
    <% end %>
    <div class="mx-auto mt-3" id="map"></div>
  </div>
  <div class="text-center mt-3">
    <h6><i class="fas fa-map-pin"></i> : <%= @record.place %></h6>
  </div>
  <table class="mt-3">
    <tr>
      <th class="text-center">チーム名</th><th class="text-center">チーム名</th>
    </tr>
    <tr>
      <td class="bg-light"><%= @record.teamname %></td><td><%= @record.enemyteam %></td>
    </tr>
    <tr>
      <th class="text-center">名前</th><th class="text-center">名前</th>
    </tr>
    <tr>
      <td class="bg-light"><%= @record.name_a %></td><td><%= @record.enemyname_a %></td>
    </tr>
    <tr>
      <td class="bg-light"><%= @record.name_b %></td><td><%= @record.enemyname_b %></td>
    </tr>
    <tr>
      <td class="bg-light"><%= @record.name_c %></td><td><%= @record.enemyname_c %></td>
    </tr>
    <tr>
      <th class="text-center">スコア</th><th class="text-center">スコア</th>
    </tr>
    <tr>
      <td class="bg-light pl-2"><%= @record.score_1 %></td><td class="pl-2"><%= @record.enemyscore_1 %></td>
    </tr>
    <tr>
      <td class="bg-light pl-2"><%= @record.score_2 %></td><td class="pl-2"><%= @record.enemyscore_2 %></td>
    </tr>
    <tr>
      <td class="bg-light pl-2"><%= @record.score_3 %></td><td class="pl-2"><%= @record.enemyscore_3 %></td>
    </tr>
    <tr>
      <td class="bg-light pl-2"><%= @record.score_4 %></td><td class="pl-2"><%= @record.enemyscore_4 %></td>
    </tr>
    <tr>
      <td class="bg-light pl-2"><%= @record.score_5 %></td><td class="pl-2"><%= @record.enemyscore_5 %></td>
    </tr>
    <tr>
      <td class="bg-light pl-2"><%= @record.score_6 %></td><td class="pl-2"><%= @record.enemyscore_6 %></td>
    </tr>
    <tr>
      <td class="bg-light pl-2"><%= @record.score_7 %></td><td class="pl-2"><%= @record.enemyscore_7 %></td>
    </tr>
    <tr>
      <td class="bg-light pl-2"><%= @record.score_8 %></td><td class="pl-2"><%= @record.enemyscore_8 %></td>
    </tr>
    <tr>
      <td class="bg-light pl-2"><%= @record.score_9 %></td><td class="pl-2"><%= @record.enemyscore_9 %></td>
    </tr>
    <tr>
      <td class="bg-light pl-2"><%= @record.score_10 %></td><td class="pl-2"><%= @record.enemyscore_10 %></td>
    </tr>
    <tr>
      <th>合計</th><th>合計</th>
    </tr>
    <tr>
      <td class="bg-light">
        <%= @total_score %>
      </td>
      <td>
        <% if @total_enemyscore > Const::WIN_SCORE %>
          <%= @over_enemyscore %>
        <% else %>
          <%= @total_enemyscore %>
        <% end %>
      </td>
    </tr>
  </table>

  <% if current_user&.id == @record.user_id %>
    <div class="text-center mt-5">
      <%= link_to "編集", edit_record_path(@record), class: "text-dark" %>
      <%= link_to "削除", record_path(@record), method: :delete, class: "text-dark" %>
    </div>
  <% end %>

  <%= link_to t("戻る"), :back, class: "text-center text-dark" %>
</div>

<script type="text/javascript">
  function initMap() {
    var test ={lat: <%= @record.latitude %>, lng: <%= @record.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15, 
              center: test
              });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '住所：<%= @record.place %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

    var marker = new google.maps.Marker({
                  position:test,
                  map: map,
                  title: contentString
                });

    marker.addListener('click', function() {
      infowindow.open(map, marker);
    });
  }
</script>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLEMAP_API'] %>&callback=initMap"></script>