config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :users, only: [:show] do
    member do
      get :following, :followers
    end
  end
  resources :follow_relationships, only: [:create, :destroy]
  resources :posts do
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :notifications, only: [:index, :destroy]
  resources :tags do
    get 'posts' => 'posts#tags'
    post 'posts' => 'posts#tags'
  end
  post '/posts/:post_id/likes' => 'likes#create'
  delete '/posts/:post_id/likes' => 'likes#destroy'
  get '/search', to: 'posts#search'
  resources :records
end

app/models/post.rb
class Post < ApplicationRecord
  paginates_per 3

  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 200 }

  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :liked_users, through: :likes, source: :users
  has_many :notifications, dependent: :destroy
  has_many :tag_post, dependent: :destroy
  has_many :tags, through: :tag_post

  mount_uploader :image, ImageUploader

  # いいね通知
  def create_notification_like!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'like'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  # コメント通知
  def create_notification_comment!(current_user, comment_id)
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

  # タグ機能
  def save_tag(save_post_tags)
    current_tags = tags.pluck(:name) unless tags.nil?
    old_tags = current_tags - save_post_tags
    new_tags = save_post_tags - current_tags
    old_tags.each do |old|
      tags.delete Tag.find_by(name: old)
    end
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      tags << new_post_tag
    end
  end

  # 検索対象のカラムを設定。入力無しなら全て表示
  def self.search(search)
    if search != ''
      Post.
        where('content LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end

  # いいね数ランキング
  def self.create_all_ranks
    Post.find(Like.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :post_current_user, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all.includes(:user, :tags, :tag_post, :likes).order(created_at: :desc).page(params[:page]).per(6)
    @user = User.find_by(params[:id])
    @tag_list = Tag.find(TagPost.group(:tag_id).order('count(tag_id) desc').limit(10).pluck(:tag_id))
    @ranks = Post.includes(:user).create_all_ranks
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    tag_list = params[:post][:name].split(nil)
    if @post.save
      @post.save_tag(tag_list)
      flash[:success] = "投稿しました！"
      redirect_to user_path(current_user)
    else
      render new_post_path
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.page(params[:page]).per(10).order("updated_at DESC")
    @like = Like.new
    @post_tags = @post.tags
  end

  def edit
    @post = Post.find(params[:id])
    @tag_list = @post.tags.pluck(:name).join(nil)
  end

  def update
    @post = Post.find(params[:id])
    tag_list = params[:post][:name].split(nil)
    if @post.update(post_params)
      @post.save_tag(tag_list)
      flash[:success] = "つぶやきを更新しました！"
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to root_path
      flash[:success] = "つぶやきを削除しました！"
    else
      render :show
    end
  end

  def tags
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @posts = @tag.post.all.includes(:user, :tags, :tag_post, :likes).order(created_at: :desc).page(params[:page]).per(6)
  end

  def search
    @tag_list = Tag.find(TagPost.group(:tag_id).order('count(tag_id) desc').limit(10).pluck(:tag_id))
    @posts = Post.search(params[:keyword]).includes([:user, :comments, :likes]).page(params[:page]).per(8).order('created_at DESC')
  end

  private

  def post_params
    params.require(:post).permit(:content, :image).merge(user_id: current_user.id)
  end

  def post_current_user
    @posts = current_user.posts
    @post = @posts.find_by(id: params[:id])
    redirect_to new_post_path unless @post
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_like.html.erb
<% if user_signed_in? %>
  <% if current_user.already_liked?(@post) %>
    <%= button_to "/posts/#{@post.id}/likes", class: "like-btn", method: :delete, remote: true do %>
      <span><i class="fas fa-heart"></i></span>
    <% end %>
  <% else %>
    <%= button_to "/posts/#{@post.id}/likes", class: "like-btn", method: :post, remote: true do %>
      <span><i class="far fa-heart"></i></span>
    <% end %>
  <% end %>
  <span><%= @post.likes.count %></span>
<% end %>

app/views/posts/_post.html.erb
<div class="container-fluid py-4 mw-md">
  <div class="border-bottom">
    <%= link_to "/posts/#{post.id}" do %>
      <div class="post-contents">
        <% if post.image.present? %>
          <img src=<%= post.image %> class="post_image">
        <% else %>
          <img src="/assets/noimage.png" class="post_image">
        <% end %>
        <p class="text-dark ml-3"><%= post.content %></p> 
      </div>
      <p class="time text-right"><%= time_ago_in_words(post.created_at) %>前</p>
    <% end %>
    <i class="far fa-heart"></i><span class="pl-1"><%= post.likes.count %></span>
  </div>
</div>

app/views/posts/_rank_post.html.erb
<% @ranks.each.with_index(1) do |post, i| %>
  <div>
    <span class="ranking text-center mb-2"><i class="fas fa-crown"></i>第<%= i %>位</span>
    <div class="rank-box rounded-lg shadow-lg px-5 py-3">
      <%= link_to post do %>
        <div class="text-center mt-1">
          <% if post.image.present? %>
            <img src=<%= post.image %> class="show-image">
          <% else %>
            <img src="/assets/noimage.png" class="show-image">
          <% end %>
        </div>
        <div class="text-center mt-2">
          <p class="text-dark"><%= post.content.truncate(10) %></p>
        </div>
        <div class="text-center">
          <% if post.user.image.present? %>
            <img src=<%= post.user.image %> class="index_image">
          <% else %>
            <img src="/assets/default.png" class="index_image">
          <% end %>
          <div class="text-center ml-1 text-dark">
            <p><%= post.user.username %></p>
            <p><%= time_ago_in_words(post.created_at) %>前</p>
          </div>
        </div>
      <% end %>
    </div> 
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container-fluid py-4 mw-md">
  <div class="text-center">
  <% if @post.image.present? %>
    <img src=<%= @post.image %> class="post_edit_image">
  <% else %>
    <img src="/assets/noimage.png" class="post_edit_image">
  <% end %>
</div>
  <%= form_with model: @post, url: post_path(@post), method: :patch, local: true do |f| %>
    <div class="form-group pt-5 mt-5">
      <h4>画像</h4>
      <%= f.file_field :image, accept: "image/jpeg, image/png, image/jpg", class: "form-control border-0" %>
    </div>
    <div class="form-group mt-5">
      <h4>つぶやき</h4>
      <%= f.text_area :content, class: "form-control" %>
    </div>
    <div class="form-group mt-5">
      <h4>タグ</h4>
      <%= f.text_field :name, placeholder: "例）練習 試合 最高記録", class: "form-control" %>
    </div>
    <div class="form-group mt-5 text-center">
      <%= f.submit "更新する", class: "btn p-2 pl-5 pr-5 text-white" %>
    </div>
    <%= link_to t("戻る"), :back, class: "text-center text-dark" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="slide-content mb-3 pb-3">
  <div class="slide-image">
    <ul class="slider mt-5">
      <li>
        <img src="/assets/mollky_image.jpeg" alt="slick-img">
      </li>
      <li>
        <img src="/assets/mollky_child.JPG" alt="slick-img">
      </li>
      <li>
        <img src="/assets/mollky_people.JPG" alt="slick-img">
      </li>
    </ul>
  </div>
  <div class="slide-text">
    <h4 class="font-weight-bold">MOLKKY RECORD</h4><br>
    <h6>未来のオリンピック競技へ</h6><br><br>
    地面に立て並べられた複数の木のピンめがけて<br>
    モルックという木の棒を投げ、
    獲得した点数を競うスポーツです。<br>
    ボウリング・カーリング・ビリヤードの各要素が詰まったようなイメージで
    ルールが至ってシンプルで分かりやすいので
    老若男女に楽しまれる生涯スポーツです。<br>
    また各地で練習会や大会を開催しており
    最近はメディアの露出も徐々に増え、ますます注目を集めています。<br>
    <div id="modal" class="text-center mt-3 text-dark">
      <button class="modal-button text-white" v-on:click="openModal"><i class="fas fa-file-alt"></i>モルックのルール<i class="fas fa-file-alt"></i></button>
      <div id="overlay" v-show="showContent" v-on:click="closeModal">
        <div id="content">
          <h2>ルール説明</h2>
          <ul class="rules-text text-left">
            <li>先攻後攻を決める</li>
            <li>先に50点ちょうどを取ったチームの勝利(先攻後攻は関係無し)</li>
            <li>2セット先取で勝利</li>
            <li>50点を超えると25点からやり直し</li>
            <li>スキットルを1本倒した場合「数字」が得点になり、2本以上倒した場合「本数」が得点になる</li>
            <li>モルックを投げるときは足元線を越えてはならない</li>
            <li>1投ごとに相手チームと交代</li>
            <li>倒したスキットルは投げたチームが立てる</li>
            <li>チーム内で3回連続0点だった場合敗北</li>
            <li>完全に地面についていないスキットルは得点にはならない</li>
          </ul>
          <div><button class="modal-button text-white" v-on:click="closeModal">閉じる</button></div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="border-top pt-5 text-center">
  <h4 class="post-title"><i class="fas fa-crown"></i>人気投稿<i class="fas fa-crown"></i></h4>
<div class="ranks border-bottom py-5">
  <%= render "rank_post" %>
</div>
<div class="container-fluid py-4 mw-md">
  <div class="text-center pt-5">
    <h4 class="post-title"><i class="fas fa-pen"></i>投稿一覧<i class="fas fa-pen"></i></h4>
  </div>
  <% if user_signed_in? %>
    <div class="mt-5 bg-light shadow-lg p-3 mb-5 rounded">
      <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |f| %>
      <div class="d-flex align-items-center justify-content-center mt-5">
          <%= f.text_field :keyword, placeholder: "投稿を検索する", class: "search-input p-2 ml-4" %>
          <button type="submit" class="ml-2"><i class="fas fa-search"></i></button>
      </div>
      <% end %>
      <div class="mt-4 text-center">
        <% @tag_list.each do |list| %>
            <%= button_to tag_posts_path(tag_id: list.id), class: "btn-light rounded-pill mt-1" do %>
              <span><%= "＃#{list.name}" %></span>
            <% end %>
        <% end %>
      </div>
    </div>
    <ul>
      <% @posts.each do |post| %>
        <li>
          <%= link_to "/posts/#{post.id}", class: "text-dark" do %>
            <div class="text-center mt-5">
              <% if post.user.image.present? %>
                <img src=<%= post.user.image %> class="index_image">
              <% else %>
                <img src="/assets/default.png" class="index_image">
              <% end %>
              <span class="pl-2"><%= post.user.username %></span>
            <div class="text-center mt-1">
              <% if post.image.present? %>
                <img src=<%= post.image %> class="show-image">
              <% else %>
                <img src="/assets/noimage.png" class="show-image">
              <% end %>
            </div>
            <div class="text-center pb-3 mb-3 border-bottom">
              <h6 class="mt-3"><%= post.content %></h6>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
    <div class="text-center">
      <%= paginate @posts %>
    </div>
  <% else %>
    <ul>
      <% @posts.each do |post| %>
        <li>
          <div class="text-center mt-5">
          <% if post.image.present? %>
            <img src=<%= post.image %> class="show-image">
          <% else %>
            <img src="/assets/noimage.png" class="show-image">
          <% end %>
          </div>
          <div class="text-center pb-3 mb-3 border-bottom">
            <h4 class="mt-5"><%= post.content %></h4>
          </div>
        </li>
      <% end %>
    </ul>
    <div class="text-center">
      <%= paginate @posts %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container-fluid py-4 mw-md">
  <%= form_with(model: @post, local: true) do |f| %>
    <div class="form-group pt-5 mt-5">
      <h4>画像</h4>
      <%= f.file_field :image, accept: "image/jpeg, image/png, image/jpg", class: "form-control border-0" %>
    </div>
    <div class="form-group mt-5">
      <h4>つぶやき</h4>
      <%= f.text_area :content, class: "form-control" %>
    </div>
    <div class="form-group mt-5">
      <h4>タグ</h4>
      <%= f.text_field :name, placeholder: "例）練習 試合 最高記録", class: "form-control" %>
    </div>
    <div class="form-group mt-5 text-center">
      <%= f.submit "投稿する", class: "btn p-2 pl-5 pr-5 text-white" %>
    </div>
    <%= link_to t("戻る"), :back, class: "text-center text-dark" %>
  <% end %>
</div>

app/views/posts/search.html.erb
<div class="container-fluid py-4 mw-md">
  <div class="mt-5 bg-light shadow-lg p-3 mb-5 rounded">
    <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |f| %>
    <div class="d-flex align-items-center justify-content-center mt-5">
        <%= f.text_field :keyword, placeholder: "投稿を検索する", class: "search-input p-2 ml-4" %>
        <button type="submit" class="ml-2"><i class="fas fa-search"></i></button>
    </div>
    <% end %>
    <div class="mt-4 text-center">
      <% @tag_list.each do |list| %>
          <%= button_to tag_posts_path(tag_id: list.id), class: "btn-light rounded-pill" do %>
            <span><%= "＃#{list.name}" %></span>
          <% end %>
      <% end %>
    </div>
  </div>

  <% if @posts.present? %>
    <ul>
      <% @posts.each do |post| %>
        <li>
          <%= link_to "/posts/#{post.id}", class: "text-dark" do %>
            <div class="text-center mt-5">
              <% if post.user.image.present? %>
                <img src=<%= post.user.image %> class="index_image">
              <% else %>
                <img src="/assets/default.png" class="index_image">
              <% end %>
              <span class="pl-2"><%= post.user.username %></span>
            <div class="text-center mt-1">
            <% if post.image.present? %>
              <img src=<%= post.image %> class="show-image">
            <% else %>
              <img src="/assets/noimage.png" class="show-image">
            <% end %>
            </div>
            <div class="text-center pb-3 mb-3 border-bottom">
              <h6 class="mt-3"><%= post.content %></h6>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p class="text-center mt-5">検索結果は0件です</p>
  <% end %>
  <div class="text-center">
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container-fluid py-4 mw-md">
  <div class="text-center mt-5">
    <%= link_to user_path(@post.user_id), class: "text-dark" do %>
      <% if @post.user.image.present? %>
        <img src=<%= @post.user.image %> class="index_image">
      <% else %>
        <img src="/assets/default.png" class="index_image">
      <% end %>
      <span class="pl-2"><%= @post.user.username %></span>
    <% end %>
  </div>
  <div class="text-center mt-5">
    <% if @post.image.present? %>
      <img src=<%= @post.image %> class="show-image">
    <% else %>
      <img src="/assets/noimage.png" class="show-image">
    <% end %>
  </div>
  <div class="text-center pb-3 mb-3 border-bottom">
    <h4 class="mt-5"><%= @post.content %></h4>
    <span class="like-<%= @post.id %>">
      <%= render "posts/like" %>
    </span>
    <div class="mt-3">
      <% @post_tags.each do |tag| %>
        <div><%= link_to "＃#{tag.name}", tag_posts_path(tag_id: tag.id) %></div>
      <% end %>
    </div>
    <% if current_user&.id == @post.user_id %>
      <div class="mt-5">
        <%= link_to "編集", edit_post_path(@post), class: "text-dark" %>
        <%= link_to "削除", post_path(@post), method: :delete, class: "text-dark" %>
      </div>
    <% end %>
  </div>
  <% if @comments %>
    <h3 class="mt-5 text-center mb-5">コメント</h3>
    <% @comments.each do |c| %>
      <div class="border-bottom">
        <p><span class="comment-contents">ユーザー名：</span> <%= link_to c.user.username, c.user, class: "text-dark" %></p>
        <p><span class="comment-contents">コメント：</span> <%= c.content %></p>
          <% if current_user&.id == c.user_id %>
            <p class="text-right"><%= link_to "削除", post_comment_path(@post, c), method: :delete, class: "text-dark" %></p>
          <% end %>
      </div>
      <br />
    <% end %>
    <div class="text-center">
    <%= paginate @comments %>
  </div>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@post, @comment], local: true) do |f| %>
      <%= f.text_area :content, class: "form-control", rows: 5 %>
      <div class="text-center mt-3">
        <%= button_tag type: "submit", class: "btn p-2 pl-5 pr-5 text-white" do %>
          コメントする
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>
  <%= link_to t("戻る"), :back, class: "text-center text-dark" %>
</div>

app/views/posts/tags.html.erb
<div class="container-fluid py-4 mw-md">
  <h4 class="mt-5 text-center"><%= "##{@tag.name}" %> のタグの投稿 <%= "#{@posts.count}件" %></h4>
  <ul>
    <% @posts.each do |post| %>
      <li>
        <%= link_to "/posts/#{post.id}", class: "text-dark" do %>
          <div class="text-center mt-5">
            <% if post.user.image.present? %>
              <img src=<%= post.user.image %> class="index_image">
            <% else %>
              <img src="/assets/default.png" class="index_image">
            <% end %>
            <span class="pl-2"><%= post.user.username %></span>
          <div class="text-center mt-1">
          <% if post.image.present? %>
            <img src=<%= post.image %> class="show-image">
          <% else %>
            <img src="/assets/noimage.png" class="show-image">
          <% end %>
          </div>
          <div class="text-center pb-3 mb-3 border-bottom">
            <h6 class="mt-3"><%= post.content %></h6>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
  <div class="text-center">
    <%= paginate @posts %>
  </div>
</div>