config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :users, only: [:show] do
    member do
      get :following, :followers
    end
  end
  resources :follow_relationships, only: [:create, :destroy]
  resources :posts do
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :notifications, only: [:index, :destroy]
  resources :tags do
    get 'posts' => 'posts#tags'
    post 'posts' => 'posts#tags'
  end
  post '/posts/:post_id/likes' => 'likes#create'
  delete '/posts/:post_id/likes' => 'likes#destroy'
  get '/search', to: 'posts#search'
  resources :records
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="mt-5 text-center alert alert-<%= msg_type %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="header-nav">
  <%= link_to "MolkkyRecord", root_path, class: "navbar-brand" %>
  <div>
    <ul class="menu">
      <% if user_signed_in? %>
        <%# ヘッダーナビボタン（ログイン時） %>
        <button type="button" class="hamburger-btn js-btn hamburger-button">
          <span class="btn-line"></span>
        </button>
        <li class="menu-list">
          <%= link_to "お知らせ", notifications_path, class: "text-white my-3" %>
        </li>
        <li class="menu-list">
          <%= link_to "#{current_user.username}", user_path(current_user.id), class: "text-white my-3" %>
        </li>
        <li class="menu-list">
          <%= link_to "つぶやき", new_post_path, class: "text-white my-3" %>
        </li>
        <li class="menu-list">
          <%= link_to "スコア投稿", new_record_path, class: "text-white my-3" %>
        </li>
        <li class="menu-list">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-white my-3" %>
        </li>
      <% else %>
        <%# ヘッダーナビボタン（未ログイン時） %>
        <button type="button" class="hamburger-btn js-btn hamburger-button">
          <span class="btn-line"></span>
        </button>
        <li class="menu-list">
          <%= link_to "かんたんログイン", users_guest_sign_in_path, method: :post, class: "text-white nav-link header-nav-link" %>
        </li>
        <li class="menu-list">
          <%= link_to "ログイン", new_user_session_path, class: "text-white nav-link header-nav-link" %>
        </li>
        <li class="menu-list">
          <%= link_to "新規登録",new_user_registration_path, class: "text-white nav-link header-nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=" crossorigin="anonymous"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MolkkyRecord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload", defer: true %>

    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
  </head>

  <body>
    <div id="loading">
      <div id="loading_box">
        <div class="loading-one animation_loading">
          <p class="loading-txt">Loading</p>
        </div>
      </div>
    </div>
    <%= render "layouts/header" %>
    <div class="container-fluid py-4 <%= devise_controller? ? "mw-md" : "mw-xl" %>">
      <%= render "layouts/flash_messages" %>
      <%= yield %>
    </div>
  </body>
</html>